spring:
  application:
    name: voting-session-service
  data:
    mongodb:
#      uri: mongodb+srv://root:T5SQVhMXftV62I2h@personal-cluster.up7z6.mongodb.net/voting_service_db?retryWrites=true&w=majority&appName=personal-cluster
      uri: ${MONGODB_URI}
  rabbitmq:
    host: ${CLOUDAMQP_URL}
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest